# Generated by Django 3.2.9 on 2022-01-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dorilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dori_nomi', models.CharField(blank=True, max_length=200)),
                ('yaroqlilik_muddati', models.DateField(blank=True)),
                ('soni_pochka', models.BigIntegerField()),
                ('turi', models.IntegerField(choices=[(1, 'Ампула'), (2, 'Таблетка'), (3, 'капсула'), (4, 'Сироп')])),
                ('pochkadagi_soni', models.IntegerField()),
                ('dorini_shtrix_kodi', models.BigIntegerField()),
                ('olingan_narxi', models.FloatField()),
                ('ustiga_foiz', models.FloatField()),
                ('sotish_narxi_pochka', models.FloatField()),
                ('sotish_narxi_dona', models.FloatField()),
                ('ishlab_chiqaruvchi', models.CharField(blank=True, max_length=200)),
                ('dori_sertifikati', models.CharField(max_length=200)),
                ('qoshimcha_malumot', models.TextField()),
                ('aktiv_dori', models.BooleanField(default=False)),
                ('max_narxi', models.FloatField()),
            ],
        ),
    ]
