# Generated by Django 3.2.9 on 2022-01-26 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dorilar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nakladnoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nakladnoy_no', models.BigIntegerField()),
                ('olingan_soni', models.IntegerField()),
                ('ishlab_chiqaruvchi', models.CharField(max_length=300)),
                ('dori_sertifikati', models.CharField(max_length=200)),
                ('olingan_narxi', models.FloatField()),
                ('ustiga_foiz', models.FloatField()),
                ('sotiladigan_narx', models.FloatField()),
                ('max_sena', models.FloatField()),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorilar.firma')),
            ],
        ),
        migrations.CreateModel(
            name='TipTovara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shtrixKod', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('shtukPachke', models.IntegerField()),
                ('tip_tovara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorilar.tiptovara')),
            ],
        ),
        migrations.DeleteModel(
            name='Dorilar',
        ),
        migrations.AddField(
            model_name='nakladnoy',
            name='tovar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dorilar.tovar'),
        ),
    ]
