# Generated by Django 3.2.9 on 2022-01-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorilar', '0002_auto_20220126_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='NakladnoyNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nakladnoy_nom', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='nakladnoy',
            name='id',
        ),
        migrations.AlterField(
            model_name='nakladnoy',
            name='nakladnoy_no',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
