# Generated by Django 3.2.9 on 2022-01-26 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorilar', '0004_auto_20220126_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nakladnoy',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='nakladnoy',
            name='tovar',
        ),
        migrations.DeleteModel(
            name='NakladnoyNo',
        ),
        migrations.RemoveField(
            model_name='tovar',
            name='tip_tovara',
        ),
        migrations.DeleteModel(
            name='Firma',
        ),
        migrations.DeleteModel(
            name='Nakladnoy',
        ),
        migrations.DeleteModel(
            name='TipTovara',
        ),
        migrations.DeleteModel(
            name='Tovar',
        ),
    ]
