# Generated by Django 3.2.9 on 2022-01-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorilar', '0008_firma_nakladnoy_nakladnoyno_tiptovara_tovar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nakladnoy',
            name='nakladnoy',
        ),
        migrations.RemoveField(
            model_name='nakladnoy',
            name='tovar',
        ),
        migrations.RemoveField(
            model_name='nakladnoyno',
            name='postavshik',
        ),
        migrations.RemoveField(
            model_name='tovar',
            name='tip_tovara',
        ),
        migrations.DeleteModel(
            name='Firma',
        ),
        migrations.DeleteModel(
            name='Nakladnoy',
        ),
        migrations.DeleteModel(
            name='NakladnoyNo',
        ),
        migrations.DeleteModel(
            name='TipTovara',
        ),
        migrations.DeleteModel(
            name='Tovar',
        ),
    ]
