# Generated by Django 3.2.9 on 2022-02-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorilar', '0013_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nakladnoy',
            name='nakladnoy',
        ),
        migrations.RemoveField(
            model_name='nakladnoy',
            name='tovar',
        ),
        migrations.RemoveField(
            model_name='nakladnoyno',
            name='postavshik',
        ),
        migrations.RemoveField(
            model_name='pereotsenka',
            name='dori',
        ),
        migrations.RemoveField(
            model_name='tovar',
            name='tip_tovara',
        ),
        migrations.DeleteModel(
            name='Firma',
        ),
        migrations.DeleteModel(
            name='Nakladnoy',
        ),
        migrations.DeleteModel(
            name='NakladnoyNo',
        ),
        migrations.DeleteModel(
            name='Pereotsenka',
        ),
        migrations.DeleteModel(
            name='TipTovara',
        ),
        migrations.DeleteModel(
            name='Tovar',
        ),
    ]
