# Generated by Django 3.2.12 on 2022-03-10 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorilar', '0017_alter_nakladnoy_date_dobavlen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pereotsenka',
        ),
    ]
