# Generated by Django 3.2.12 on 2022-03-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorilar', '0019_pereotsenka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spisaniya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nakladnoy', models.BigIntegerField(unique=True)),
                ('tovar', models.BigIntegerField()),
                ('olingan_soni', models.IntegerField()),
                ('ishlab_chiqaruvchi', models.CharField(max_length=300)),
                ('dori_sertifikati', models.CharField(max_length=200)),
                ('srok', models.DateField()),
                ('date_dobavlen', models.DateField(auto_now_add=True)),
                ('olingan_narxi', models.FloatField()),
                ('ustiga_foiz', models.FloatField()),
                ('sotiladigan_narx', models.FloatField()),
                ('spisano', models.BooleanField()),
            ],
        ),
    ]
