# Generated by Django 3.2.12 on 2022-03-11 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorilar', '0020_spisaniya'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spisaniya',
        ),
    ]
