# Generated by Django 3.2.9 on 2022-03-31 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kassir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arxiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nakladnoy', models.BinaryField()),
                ('tovar_name', models.CharField(max_length=500)),
                ('tovar_shtrix_kod', models.BigIntegerField()),
                ('tovar_shtuk_pachke', models.IntegerField()),
                ('tovar_type', models.CharField(max_length=500)),
                ('narx', models.FloatField()),
                ('srok', models.DateField()),
                ('soni', models.BigIntegerField()),
                ('summa', models.FloatField()),
                ('sold', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kassir.kassir')),
            ],
        ),
    ]
