# Generated by Django 3.2.9 on 2022-04-04 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kassa', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arxiv',
        ),
    ]
