# Generated by Django 3.2.9 on 2022-04-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kassa', '0003_arxiv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arxiv',
            name='nakladnoy',
            field=models.BigIntegerField(),
        ),
    ]
